---
# tasks file for hadoop_master
- name: For copying Hadoop and Jdk rpm file to Namenode machine
  copy:
    src: files/
    dest: /root/
- name: For storing and getting facts about installed packages
  package_facts:
        manager: "auto" 
- name: For installing jdk
  yum:
     name: /root/jdk-8u171-linux-x64.rpm
     state: present
- name: For installing Hadoop software
  command: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm --force"
  when: "'hadoop' not in ansible_facts.packages"

- name: For creating dirrectory in namenode machine
  file:
       path: /root/{{dir_namenode}}
       state: directory
- name: For configuring hadoop's hdfs-site.xml file
  blockinfile:
        path: /etc/hadoop/hdfs-site.xml
        insertafter: "<configuration>"
        block: |    
            <property>
            <name>dfs.name.dir</name>
            <value>{{dir_namenode}}</value>
            </property>
- name: For Configuring core-site.xml file of hadoop
  blockinfile:
        path: /etc/hadoop/core-site.xml
        insertafter: "<configuration>"
        block: |
            <property>
            <name>fs.default.name</name>
            <value>hdfs://0.0.0.0:9001</value>
            </property>
- name: For getting hadoop namenode started or not
  command: "jps"
  register: x
- name: For Printing Jps command output
  debug:
        var: x['stdout']
- name: Command for formatting namenode folder
  command: "echo y | hadoop namenode -format "
  when: "'NameNode' not in x['stdout']"
  ignore_errors: true
- name: command for starting namenode
  command: "hadoop-daemon.sh start namenode"
  when: "'NameNode' not in x['stdout']"
